config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'swipes/index', to: 'swipes#index'

  # get 'swipes/new', to: 'swipes#new'
  # get 'swipes', to: 'swipes#create'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile', to: 'pages#profile'

  resources :swipes, only: [:index, :new, :create]

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <%= render 'shared/fyne_logo'  %>
    <h1>fyne</h1>
    <p>find your next experiences</p>
    <a class="btn btn-start btn-lg">Start</a>
  </div>
</div>

app/views/shared/_calendar_logo.html.erb
<%= link_to swipes_path, class: color, id: "navbar-item" do %>
  <i class="fa fa-calendar" aria-hidden="true"></i>
<% end %>

app/views/shared/_cards.html.erb
<div class="card-container-index">
  <div class="event-info-box">
    <div id="event-hour-box">
      <%= event.start_time.strftime('%H:%M') %>
    </div>
    <div class= "<%= event.category.downcase %>">
      <div id="event-info-box-aesthetic-background">
      </div>
      <div id="event-subcategory-box" >
        <%= event.subcategory.capitalize.gsub(/_/," ")  %>
      </div>
    </div>
  </div>

  <% if event.photouploaded %>
    <% event_image = cl_image_path event.photouploaded.path, gravity: :south %>
  <% elsif event.photo %>
    <% event_image = image_path event.photo %>
  <% else %>
    <% event_image = image_path "event-placeholder-photo-banner.jpg" %>
  <% end %>

  <div class="card-wrapper-index">
    <div class="card-index" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= event_image %>')" >

      <div class="card-description-index">
        <% if event.name.size >= 42 %>
          <h2><%= event.name[0..41] %>...</h2>
        <% else %>
          <h2><%= event.name %></h2>
        <% end %>
        <p>
          <i class="fa fa-map-marker" aria-hidden="true" ></i>
          <% address_of_event = "#{event.street_address}, #{event.city}, #{event.country}" %>
          <% if address_of_event.size >= 42 %>
            <span><%= address_of_event[0..41] %>...</span>
          <% else %>
            <span><%= address_of_event %></span>
          <% end %>
        </p>
      </div>
    <%= link_to '', event_path(event), class: "card-link-index" %>
  </div>

    <div class="card-footer-index">
      <p>
      <%= pluralize((event.swipe.where(interested: true).count), 'person') %> interested
      </p>
      <%=link_to "https://www.facebook.com/sharer/sharer.php?u=https://fyne.herokuapp.com/events/#{event.id}", target: :_blank do %>
        <i class="fa fa-share share-fb-index" aria-hidden="true"></i>
      <% end %>
       <% if (event.url != nil) & (event.url != "") %>
        <div>
          <%=link_to "#{event.url}", target: :_blank do %>
            <i class="fa fa-bolt book-btn-index" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_event_infos.html.erb
<div class="container">
  <div class="main-info-container">
    <div class="main-info">
      <div class="event-name">
        <% if @event.venue_name != nil %>
          <h2> <%= @event.name %> @ <%= @event.venue_name %></h2>
        <% else %>
          <h2> <%= @event.name %> </h2>
        <% end %>
      </div>

      <p class="category-tag <%= @event.category.downcase %>-tag"> <%= @event.subcategory.gsub(/_/," ").capitalize %> </p>
    </div>

    <div class="main-info-btns">
      <% if (@event.url != nil) & (@event.url != "") & page_show %>
         <%=link_to "#{@event.url}", target: :_blank do %>
          <i class="fa fa-bolt btn-book" aria-hidden="true"></i>
        <% end %>
      <% end %>

      <%=link_to "https://www.facebook.com/sharer/sharer.php?u=https://fyne.herokuapp.com/events/#{@event.id}", target: :_blank do %>
        <i class="fa fa-share share-fb" aria-hidden="true"></i>
      <% end %>

    </div>
  </div>
  <div id="secondary-infos">
    <div id="date" class="e-info">
      <i class="fa fa-calendar-o" aria-hidden="true"></i>
      <p class="inline"> <%= @event.start_time.strftime('%A, %b %dth at %H:%M') %> </p>

      <% if @event.end_time != nil && @event.start_time.strftime('%b %dth %Y') == @event.end_time.strftime('%b %dth %Y') %>
        <h6 class="indication"> <%= @event.start_time.strftime('From %b %dth %Y at %H:%M') %> to <%= @event.end_time.strftime('%H:%M') %></h6>
      <% else %>
        <h6 class="indication"> From <%= @event.start_time.strftime('%b %dth %Y at %H:%M') %></h6>
        <% if @event.end_time != nil %>
          <h6 class="indication"> To <%= @event.end_time.strftime('%b %dth %Y at %H:%M') %></h6>
        <% end %>
      <% end %>
    </div>

    <div id="location" class="e-info" >
      <table>
        <tr>
          <td valign="top">
            <i class="fa fa-map-marker" aria-hidden="true" style="padding-left: 3px; padding-right:6px"></i>
          </td>
          <td>
            <p class="inline"> <%= @event.street_address %> <%= @event.zip_code %> <%= @event.city %>, <%= @event.country %></p>
          </td>
        </tr>
      </table>
      <div class="text-center" id="map" style="width: 100%; height: 200px;">
        <%= render 'shared/map' %>
      </div>
    </div>

  <hr>

    <% if (@event.description != nil) & (@event.description != "")%>
      <div id="description" class="e-info">
        <table>
          <tr>
            <td valign="top">
              <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 3px; padding-right:6px"></i>
            </td>
            <td class="event-description">
              <p class="inline"> <%= @event.description %></p>
            </td>
          </tr>
        </table>
      </div>
      <hr>
    <% end %>


  <% unless @event.user == current_user %>
    <div id="organizer" class="e-info">
      <table>
        <tr>
          <td valign="top">
            <i class="fa fa-user" style="padding-right: 6px" aria-hidden="true"></i>
          </td>
          <td>
            <p class="inline"> Organized by <%= @event.user.first_name %> <%= @event.user.last_name %></p>
          </td>
        </tr>
      </table>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>

  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close close-fyne" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close close-fyne" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
  <div class="background-card">
    <div class="row">
      <%= simple_form_for(@event) do |f| %>
      <div class="col-xs-12 col-lg-6">
        <%= f.input :name %>
        <%= f.input :photouploaded, as: :attachinary, label: 'Photo' %>
      </div>
      <div class="col-xs-12 col-lg-6">
        <%#= f.input :category, prompt: 'Please choose your category', collection: ["Art & Culture", "Music", "Films & Series", "Sports", "Games", "Wellness & Health", "Spirituality", "Non-profit", "Tasting & Restauration", "Crafting", "Party", "Business", "Politics", "Other"] %>
        <%= f.input :category, prompt: 'Please choose your category', collection: ["music", "festivals_parades", "singles_social", "comedy", "movies_film", "performing_arts",  "books", "art", "attractions", "outdoors_recreation", "community", "clubs_associations", "sports", "support", "food", "fundraisers", "religion_spirituality", "technology", "science", "learning_education", "family_fun_kids", "schools_alumni", "sales", "business", "conference", "holiday", "politics_activism", "animals", "other"] %>
        <% if page_new %>
        <%= f.input :subcategory, collection: ["Please select a category first"], prompt: 'Please choose your subcategory' %>
        <% else %>
          <%= f.input :subcategory, collection: @subcats_hash[@event.category], priority: @event.subcategory  %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="background-card">
    <div class="row">
      <div class="col-xs-12 col-lg-6">
        <%= f.input :description %>
        <%= f.input :url, label: "Url (useful for booking)" %>
      </div>
    </div>
  </div>


  <!-- ["music", "conference", "comedy", "learning_education", "family_fun_kids",  "festivals_parades",  "movies_film",  "food", "fundraisers",  "art",  "support",  "holiday",  "books",  "attractions",  "community",  "business", "singles_social", "schools_alumni", "clubs_associations", "outdoors_recreation",  "performing_arts",  "animals",  "politics_activism",  "sales",  "science",  "religion_spirituality",  "technology", "sports", "other"] -->

  <!-- ["Art & Culture", "Music", "Films & Series", "Sports", "Games", "Wellness & Health", "Spirituality", "Non-profit", "Tasting & Restauration", "Crafting", "Party", "Business", "Politics", "Other"] -->

  <div class="background-card">
    <div class="row">
      <div class="col-xs-12 col-lg-6">
          <%= f.input :start_time %>
          <%= f.input :end_time %>
      </div>

      <div class="col-xs-12 col-lg-6">
        <%= f.input :venue_name %>
        <%= f.input :street_address %>
        <%= f.input :zip_code %>
        <%= f.input :city %>
        <%= f.input :country %>
      </div>
    </div>
  </div>



  <div class="row">
    <div class="col-xs-12">
      <div class="text-center">
        <%= f.submit "Save changes", class: "btn btn-fyne btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
console.log('Hello World from categories')


const categoryField = document.getElementById('event_category')
const subcategoryField = document.getElementById('event_subcategory')


const subcats_hash = {};
subcats_hash["music"] = ["music", "music_blues",  "music_classical",  "music_country",  "music_dance",  "music_easy_listening", "music_electronic", "music_folk", "music_jazz", "music_latin",  "music_newage", "music_opera",  "music_rb", "music_reggae", "music_vocal",  "music_rap_hiphop", "music_metal",  "music_religious",  "music_rock", "music_pop",  "music_world",  "music_alternative",  "music_childrens"];
subcats_hash["conference"] = ["conference", "conference_career", "conference_convention", "conference_seminar", "conference_talkslectures"];
subcats_hash["comedy"] = ["comedy"];
subcats_hash["learning_education"] = ["learning_education", "learning_education_classworkshop"];
subcats_hash["family_fun_kids"] = ["family_fun_kids"];
subcats_hash["festivals_parades"] = ["festivals_parades", "festivals_parades_circus", "festivals_parades_festival", "festivals_parades_fairs", "festivals_parades_parade"];
subcats_hash["movies_film"] = ["movies_film", "movies_film_filmfestival"];
subcats_hash["food"] = ["food", "food_beer", "food_wine", "food_farmersmarket", "food_tastings"];
subcats_hash["fundraisers"] = ["fundraisers", "fundraisers_blooddrive", "fundraisers_volunteer"];
subcats_hash["art"] = ["art",
"art_antiques",
"art_painting",
"art_photography",
"art_artexhibits",
"art_artsandcrafts",
"art_fashion"];
subcats_hash["support"] = ["support",
"support_fitness",
"support_seniorhealth",
"support_support",
"support_yoga"];
subcats_hash["holiday"] = ["holiday"];
subcats_hash["books"] = ["books",
"books_poetry"];
subcats_hash["attractions"] = ["attractions"];
subcats_hash["community"] = ["community",
"community_library",
"community_holiday",
"community_seasonal"];
subcats_hash["business"] = ["business"];
subcats_hash["singles_social"] = ["singles_social",
"singles_social_trivianight",
"singles_social_comedy",
"singles_social_bars",
"singles_social_dating",
"singles_social_karaoke",
"singles_social_openmic"];
subcats_hash["schools_alumni"] = ["schools_alumni"];
subcats_hash["clubs_associations"] = ["clubs_associations"];
subcats_hash["outdoors_recreation"] = ["outdoors_recreation",
"outdoors_recreation_cycling",
"outdoors_recreation_hiking",
"outdoors_recreation_nature",
"outdoors_recreation_running"];
subcats_hash["performing_arts"] = ["performing_arts",
"performing_arts_cabaret",
"performing_arts_opera",
"performing_arts_dance",
"performing_arts_musical",
"performing_arts_ballet",
"performing_arts_comedy",
"performing_arts_theatre"];
subcats_hash["animals"] = ["animals",
"animals_cats",
"animals_dogs"];
subcats_hash["politics_activism"] = ["politics_activism"];
subcats_hash["sales"] = ["sales",
"sales_auction",
"sales_craftshow",
"sales_fleamarket",
"sales_yardsale",
"sales_retail"];
subcats_hash["science"] = ["science"];
subcats_hash["religion_spirituality"] = ["religion_spirituality"];
subcats_hash["sports"] = ["sports",
"sports_autoracing",
"sports_dance",
"sports_gymnastics",
"sports_iceskatingskiing",
"sports_softball",
"sports_swimmingdiving",
"sports_volleyball",
"sports_baseball",
"sports_basketball",
"sports_cricket",
"sports_football",
"sports_golf",
"sports_hockey",
"sports_rugby",
"sports_soccer",
"sports_tennis",
"sports_wrestling"];
subcats_hash["technology"] = ["technology",
"technology_computer"];
subcats_hash["other"] = ["other"];

subcats_hash["Films & Series"] = ["Action", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Musical", "Romance", "Sport", "War", "Western"];
subcats_hash["Sports"] = ["Football", "Rugby", "Tennis", "Formula 1", "Auto/moto", "Basket", "Handball", "Golf", "Cycle", "Winter sports", "Athletism", "Swimming", "Volley-ball", "Other sports"];
subcats_hash["Games"] = ["Games"];
subcats_hash["Wellness & Health"] = ["Dancing", "Fitness", "Health"];
subcats_hash["Spirituality"] = ["Spirituality"];
subcats_hash["Non-profit"] = ["Non-profit"];
subcats_hash["Tasting & Restauration"] = ["Food tasting", "Drink tasting"];
subcats_hash["Crafting"] = ["Crafting (General)", "Gardening", "Home"];
subcats_hash["Party"] = ["Party"];
subcats_hash["Business"] = ["Networking", "Shopping", "Conference"];
subcats_hash["Politics"] = ["Politics"];
subcats_hash["Other"] = ["Other"];

<!-- subcats_hash["music"] = ["music", "music_blues",  "music_classical",  "music_country",  "music_dance",  "music_easy_listening", "music_electronic", "music_folk", "music_jazz", "music_latin",  "music_newage", "music_opera",  "music_rb", "music_reggae", "music_vocal",  "music_rap_hiphop", "music_metal",  "music_religious",  "music_rock", "music_pop",  "music_world",  "music_alternative",  "music_childrens"];
 -->

<!-- subcats_hash["music"] = ["music", "music_blues",  "music_classical",  "music_country",  "music_dance",  "music_easy_listening", "music_electronic", "music_folk", "music_jazz", "music_latin",  "music_newage", "music_opera",  "music_rb", "music_reggae", "music_vocal",  "music_rap_hiphop", "music_metal",  "music_religious",  "music_rock", "music_pop",  "music_world",  "music_alternative",  "music_childrens"];
subcats_hash["conference"] = ["conference", "conference_career", "conference_convention", "conference_seminar", "conference_talkslectures"];
subcats_hash["comedy"] = ["comedy"];
subcats_hash["learning_education"] = ["learning_education",
"learning_education_classworkshop"];
subcats_hash["family_fun_kids"] = ["family_fun_kids"];
subcats_hash["festivals_parades"] = ["festivals_parades", "festivals_parades_circus", "festivals_parades_festival", "festivals_parades_fairs", "festivals_parades_parade"];
subcats_hash["movies_film"] = ["movies_film", "movies_film_filmfestival"];
subcats_hash["food"] = ["food",
"food_beer",
"food_wine",
"food_farmersmarket",
"food_tastings"];
subcats_hash["fundraisers"] = ["fundraisers",
"fundraisers_blooddrive",
"fundraisers_volunteer"];
subcats_hash["art"] = ["art",
"art_antiques",
"art_painting",
"art_photography",
"art_artexhibits",
"art_artsandcrafts",
"art_fashion"];
subcats_hash["support"] = ["support",
"support_fitness",
"support_seniorhealth",
"support_support",
"support_yoga"];
subcats_hash["holiday"] = ["holiday"];
subcats_hash["books"] = ["books",
"books_poetry"];
subcats_hash["attractions"] = ["attractions"];
subcats_hash["community"] = ["community",
"community_library",
"community_holiday",
"community_seasonal"];
subcats_hash["business"] = ["business"];
subcats_hash["singles_social"] = ["singles_social",
"singles_social_trivianight",
"singles_social_comedy",
"singles_social_bars",
"singles_social_dating",
"singles_social_karaoke",
"singles_social_openmic"];
subcats_hash["schools_alumni"] = ["schools_alumni"];
subcats_hash["clubs_associations"] = ["clubs_associations"];
subcats_hash["outdoors_recreation"] = ["outdoors_recreation",
"outdoors_recreation_cycling",
"outdoors_recreation_hiking",
"outdoors_recreation_nature",
"outdoors_recreation_running"];
subcats_hash["performing_arts"] = ["performing_arts",
"performing_arts_cabaret",
"performing_arts_opera",
"performing_arts_dance",
"performing_arts_musical",
"performing_arts_ballet",
"performing_arts_comedy",
"performing_arts_theatre"];
subcats_hash["animals"] = ["animals",
"animals_cats",
"animals_dogs"];
subcats_hash["politics_activism"] = ["politics_activism"];
subcats_hash["sales"] = ["sales",
"sales_auction",
"sales_craftshow",
"sales_fleamarket",
"sales_yardsale",
"sales_retail"];
subcats_hash["science"] = ["science"];
subcats_hash["religion_spirituality"] = ["religion_spirituality"];
subcats_hash["sports"] = ["sports",
"sports_autoracing",
"sports_dance",
"sports_gymnastics",
"sports_iceskatingskiing",
"sports_softball",
"sports_swimmingdiving",
"sports_volleyball",
"sports_baseball",
"sports_basketball",
"sports_cricket",
"sports_football",
"sports_golf",
"sports_hockey",
"sports_rugby",
"sports_soccer",
"sports_tennis",
"sports_wrestling"];
subcats_hash["technology"] = ["technology",
"technology_computer"];
subcats_hash["other"] = ["other"];
 -->

document.addEventListener("DOMContentLoaded", () => {
  let cat_options = categoryField.querySelectorAll("option");

  cat_options.forEach((option) => {
    option.innerText = option.innerText.charAt(0).toUpperCase() + option.innerText.slice(1).replace("_", " ").replace("_", " ");

  })


  let subcat_options = subcategoryField.querySelectorAll("option");

  subcat_options.forEach((option) => {
    option.innerText = option.innerText.charAt(0).toUpperCase() + option.innerText.slice(1).replace("_", " ").replace("_", " ");

  })



});

function makeFieldsWork(event) {
    let categorySelected = categoryField.value;
  let subcategories_matching = subcats_hash[categorySelected];

  let subcat_options = subcategoryField.querySelectorAll("option");



  subcategoryField.innerHTML = "";


  subcategories_matching.forEach((subcategory) => {
    subcategoryField.insertAdjacentHTML("beforeend", `<option value="${subcategory}">${subcategory.charAt(0).toUpperCase() + subcategory.slice(1).replace("_", " ").replace("_", " ")}</option>`);
  });
}





categoryField.addEventListener("change",(event) => {

makeFieldsWork(event)

});



  <% end %>
<% end %>

app/views/shared/_fyne_logo.html.erb
  <?xml version="1.0" encoding="UTF-8"?>
  <svg width="<%= width %>" height="<%= 1.73 * width %>" viewBox="0 0 137 247" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="logo-navbar-container">
      <!-- Generator: Sketch 48.1 (47250) - http://www.bohemiancoding.com/sketch -->
      <title>Combined Shape</title>
      <desc>Created with Sketch.</desc>
      <defs></defs>
      <g id="LANDING-PAGE" class="<%= color %>" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" transform="translate(-118.000000, -92.000000)" >
          <path d="M210.944374,110.182468 L196.913428,189.755916 L245.027358,199.108316 L210.944374,110.182468 Z M206.011785,109.362716 L135.998214,177.915197 L192.004545,188.801725 L206.011785,109.362716 Z M181.553564,276.866036 L243.898778,203.982526 L196.045055,194.680704 L181.553564,276.866036 Z M177.138544,273.111004 L191.136172,193.726514 L137.93157,183.384587 L177.138544,273.111004 Z M129.406785,181.727537 L129.358548,181.718161 L129.372138,181.648246 L126.933243,176.066757 L211.914063,92.859375 L254.119141,202.976562 L180.512901,289.024565 C180.506828,289.084159 180.500659,289.143765 180.494393,289.203383 C177.287472,319.715201 149.953032,341.850194 119.441214,338.643272 C118.959343,338.592626 118.479562,338.535961 118.001937,338.473362 L118.487489,333.85365 C118.635996,333.871051 118.784801,333.887589 118.933901,333.903261 C144.139316,336.552456 172.215192,313.817061 174.864388,288.611645 C174.950192,287.795275 175.009862,286.981219 175.044144,286.170094 L129.406785,181.727537 Z" id="Combined-Shape" ></path>
      </g>
  </svg>
<!-- fill="<%= color %>" -->

app/views/shared/_map.html.erb
<% content_for(:after_js) do %>
  <script>
    var styles = [
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#f7f1df"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#d0e3b4"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.medical",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#fbd3da"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#bde6ab"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffe15f"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#efd151"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "black"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#cfb2db"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#a2daf2"
            }
        ]
    }
];


    var handler = Gmaps.build('Google');
    handler.buildMap({
      provider: {
        scrollwheel: false,
        styles: styles
      },
      internal: { id: 'map' }}, function() {
        markers = handler.addMarkers(<%= raw @marker.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
    // var currCenter = map.getCenter();
    });
  </script>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <% if user_signed_in? %>
    <div>
      <%= render 'shared/profile_logo', color: profile_color %>
    </div>
    <div>
      <%= link_to new_swipe_path do %>
        <%= render 'shared/fyne_logo', color: fyne_color, width: 23  %>
      <% end %>
    </div>

    <div>
      <%= render 'shared/calendar_logo', color: calendar_color %>
    </div>
  <% end %>

</div>

app/views/shared/_profile_logo.html.erb
<%= link_to profile_path, class: color, id: "navbar-item" do %>
  <i class="fa fa-user" aria-hidden="true" fill= "yellow"></i>
<% end %>

app/views/shared/_swipe_new.html.erb
  <% if event != nil %>
    <div id="container-new-swipe">
      <div id="container-new" class="container-new">
        <div class="row-card">
          <div id="photo-container-new">
            <% if event.photouploaded %>
              <div id="photo" class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path event.photouploaded.path %>');">
            <% else %>
              <div id="photo" class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= event.photo %>');">
            <% end %>
              <div id="main-infos-new" class="card-description ">
                <h2><%= event.name %></h2>
                <p id="subcat"><%= event.subcategory.capitalize.gsub(/_/," ")  %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row-controls">
          <div class="">
            <div id="command-btn-group" class="controls">
              <div class="control-btn btn-dislike">
                <%= link_to swipes_path(swipe: {event_id: event.id, user_id: current_user.id, interested: false}), method: :post, :remote => true do %>
                  <i class="fa fa-times fa-3x button dislike" aria-hidden="true"></i>
                <% end %>
              </div>
              <div class="control-btn btn-like">
                <%= link_to swipes_path(swipe: {event_id: event.id, user_id: current_user.id, interested: true}), method: :post, :remote => true do %>
                    <i class="fa fa-heart fa-3x button like" aria-hidden="true"></i>
                  <%#= image_tag "like.png", {class: "img-circle button"}%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div id="event-infos" class="custom-hide">
         <%= render partial:'shared/event_infos', locals: { page_show: false } %>
        </div>
      </div>
    </div>

  <!-- if all the events have already been swiped by the current_user : -->

  <% else %>
    <div class="container-new">
      <div class="walter text-center">
        <h1>Introducing Walter</h1>
        <p>The #1 event finder in the world</p>
        <%= render 'shared/walter' %>
      </div>
    </div>
  <%# EventService.new(city: current_user.city).call %>
  <%# redirect_to new_swipe_path %>
  <% end %>

app/views/shared/_welcome_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <div class="banner-logo">
      <%= render 'shared/fyne_logo', color: "white", width: 95 %>
    </div>
    <h1>fyne</h1>
    <p>find your next experiences</p>
      <%= link_to "Sign up with Facebook", user_facebook_omniauth_authorize_path, class: "btn btn-fyne btn-facebook" %>
      <%= link_to "Sign up with Email", new_user_registration_path, class: "btn btn-fyne btn-email" %>
      <br>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-fyne btn-primary btn-fyne btn-fyne-login" %>

    <!-- <p>Have an account? <%#= link_to "Log in", new_user_session_path %></p> -->
  </div>
</div>