config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'swipes/index', to: 'swipes#index'

  # get 'swipes/new', to: 'swipes#new'
  # get 'swipes', to: 'swipes#create'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile', to: 'pages#profile'

  resources :swipes, only: [:index, :new, :create]

  mount Attachinary::Engine => "/attachinary"

end

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

app/views/pages/profile.html.erb
<%= render 'shared/navbar', profile_color: "active", calendar_color: "inactive", fyne_color: "inactive" %>

<% content_for(:title) do %>
  <%= @user.first_name %> <%= @user.last_name %>
<% end %>

<div class="container">
  <div class="user-img-name">
    <div class="user-img">
      <% if current_user.facebook_picture_url? %>
        <%= image_tag current_user.facebook_picture_url, class: "avatar-profile" %>
      <% elsif @user.photo? %>
        <%= cl_image_tag( @user.photo.path, :width=>135, :height=>135, :gravity=>"face", :crop=>"thumb", class: "avatar-profile")  %>
      <% else %>
        <%= image_tag 'avatar.jpg', class: "avatar-profile" %>
      <% end %>
    </div>
  </div>
  <div class="user-info text-center">
    <h1 class="user-name text-center"><%= @user.first_name %> <%= @user.last_name %></h1>

    <h2><%= Event.count %></h2>
    <p>events available on fyne</p>


    <% if @user.city == nil %>
    <% else %>
      <% number_of_events_to_discover = Event.where(city: @user.city).count - Swipe.where(user: @user, event: Event.where(city: @user.city)).count %>
      <% if number_of_events_to_discover >= 0 %>
        <h2><%= number_of_events_to_discover %></h2>
      <% else %>
        <h2>0</h2>
      <% end %>
      <p>events not discovered yet in <%= @user.city %></p>
    <% end %>

    <h2><%= Event.where(user: @user).count %></h2>
    <p>events you created</p>

    <h2><%= Swipe.where(interested: true).joins(:event).where(events: {user: @user}).count %></h2>
    <p>likes received</p>

  </div>

  <div class="row buttons btn-group-fyne btn-top-move">
    <%= link_to "Update", edit_user_registration_path, class: "btn btn-fyne btn-primary" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-fyne btn-danger" %>

    <% if @user.admin %>
      <%= link_to "Admin page", rails_admin_path, class: "btn btn-fyne btn-success" %>
    <% end %>

  </div>
</div>